<style>
    * {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        box-sizing: border-box;
        color: rgb(39, 38, 38);
    }
</style>
<div style="background-color: #FEFEFE;">
    <center>
        <div>
            <img src="{{asset('storage/images/logo.png')}}" style="width: 100px;" />
            <p class="header-text"><strong>CPSU Graduate School</strong></p>
        </div>
        <div style="background-color: rgb(235, 245, 242);overflow: hidden;width: 500px; text-align: left;position: relative;">
            <div class="email-content">
                @yield('content')
            </div>
            <div style="background-color: rgb(191, 197, 190);width: 100%;color: rgb(39, 38, 38);font-size: 10pt;padding: 10px; text-align: center;">
                <span class="margin-right: 10px;">
                    &copy; CPSU Grad School 2024
                </span>
                |
                <a href='tel:+639123456789' style="margin-left: 10px; margin-right: 10px; text-decoration: none; color: rgb(93 123 119); ">+639123456789</a>
                |
                <a href='mailto:info@cpsugradschool.edu.ph' style="margin-left: 10px; text-decoration: none; color: rgb(93 123 119);">info@cpsugradschool.edu.ph</a>
            </div>
        </div>
        <p><small>This email is autogenerated do not reply.</small></p>
    </center>
</div>